FROM python:3.8-alpine

# set working directory
WORKDIR /usr/src/app

RUN apk add curl
# #Download the desired package(s)
RUN curl -O https://download.microsoft.com/download/e/4/e/e4e67866-dffd-428c-aac7-8d28ddafb39b/msodbcsql17_17.7.1.1-1_amd64.apk
RUN curl -O https://download.microsoft.com/download/e/4/e/e4e67866-dffd-428c-aac7-8d28ddafb39b/mssql-tools_17.7.1.1-1_amd64.apk

# #Install the package(s)
RUN apk add --allow-untrusted msodbcsql17_17.7.1.1-1_amd64.apk
RUN apk add --allow-untrusted mssql-tools_17.7.1.1-1_amd64.apk

# copy project file
COPY requirements.txt .

# install dependencies
RUN apk add --update g++ unixodbc-dev
RUN pip install -r requirements.txt

# copy all project
COPY . .

# run test
CMD sleep 60 && python ./test.py
